Repository gh05tdog/Sudoku_Solver, pull requests merged in 2024-06, with the labels that each got.

#62 Removed the start game button
  src/main/java/dk/dtu/game/core/SudokuGame.java
  src/test/java/dk/dtu/core/SudokuGameTest.java
Labels: enhancement

#64 Removes wrong numbers before adding new in hints
  .idea/misc.xml
  src/main/java/dk/dtu/SudokuSolverApp.java
  src/main/java/dk/dtu/engine/graphics/Cell.java
  src/main/java/dk/dtu/engine/graphics/NumberHub.java
  src/main/java/dk/dtu/engine/graphics/SudokuBoardCanvas.java
  src/main/java/dk/dtu/game/core/SudokuGame.java
  src/test/java/dk/dtu/core/SudokuGameTest.java
Labels: enhancement

#67 Added leaderboard with sqlite
  .gitignore
  .idea/.gitignore
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/encodings.xml
  .idea/material_theme_project_new.xml
  .idea/misc.xml
  .idea/sonarlint.xml
  .idea/uiDesigner.xml
  .idea/vcs.xml
  pom.xml
  src/main/java/dk/dtu/SudokuSolverApp.java
  src/main/java/dk/dtu/engine/utility/DatabaseSetup.java
  src/main/java/dk/dtu/engine/utility/Leaderboard.java
  src/main/java/dk/dtu/engine/utility/TimerFunction.java
  src/main/java/dk/dtu/engine/utility/UpdateLeaderboard.java
  src/main/java/dk/dtu/game/core/StartMenu.java
  src/main/java/dk/dtu/game/core/SudokuGame.java
  src/main/java/dk/dtu/game/core/solver/SolverAlgorithm.java
  src/test/java/dk/dtu/core/DatabaseSetupTest.java
  src/test/java/dk/dtu/core/LeaderboardTest.java
  src/test/java/dk/dtu/core/SudokuGameTest.java
Labels: enhancement

#72 Fixed the restart button not working
  src/main/java/dk/dtu/game/core/SudokuGame.java
Labels: bug

#73 Added-DataBaseTest
  src/main/java/dk/dtu/engine/utility/UpdateLeaderboard.java
  src/main/java/dk/dtu/game/core/SudokuGame.java
  src/test/java/dk/dtu/core/LeaderboardTest.java
Labels: enhancement

#78 Made gamerules
  src/main/java/dk/dtu/engine/core/StartMenuWindowManager.java
  src/main/java/dk/dtu/engine/core/WindowManager.java
  src/main/java/dk/dtu/engine/graphics/Cell.java
  src/main/java/dk/dtu/engine/graphics/GameRulePopup.java
  src/main/java/dk/dtu/engine/graphics/SudokuBoardCanvas.java
  src/main/java/dk/dtu/engine/utility/JSwitchBox.java
  src/main/java/dk/dtu/game/core/Board.java
  src/main/java/dk/dtu/game/core/Config.java
  src/main/java/dk/dtu/game/core/StartMenu.java
  src/main/java/dk/dtu/game/core/SudokuGame.java
  src/main/java/dk/dtu/game/core/solver/algorithmx/AlgorithmXSolver.java
  src/main/java/dk/dtu/game/core/solver/bruteforce/BruteForceAlgorithm.java
  src/main/resources/460px-Heart8.png
  src/main/resources/pixil-frame-0.png
  src/main/resources/redHeart.png
  src/test/java/dk/dtu/core/SudokuGameTest.java
  sudoku.db
Labels: enhancement

#75 Added Local Compete Mode
  src/main/java/dk/dtu/engine/core/GameEngine.java
  src/main/java/dk/dtu/engine/core/StartMenuWindowManager.java
  src/main/java/dk/dtu/engine/utility/GameClient.java
  src/main/java/dk/dtu/engine/utility/GameServer.java
  src/main/java/dk/dtu/game/core/StartMenu.java
  src/main/java/dk/dtu/game/core/SudokuGame.java
  src/main/java/dk/dtu/game/core/solver/algorithmx/AlgorithmXSolver.java
  src/test/java/dk/dtu/core/onlineTests/GameClientTest.java
  src/test/java/dk/dtu/core/onlineTests/GameServerTests.java
Labels: enhancement

#80 Made it so it is visibly shown then you have placed all numbers
  src/main/java/dk/dtu/engine/graphics/NumberHub.java
  src/main/java/dk/dtu/game/core/SudokuGame.java
Labels: enhancement

#88 Made number of lives a variable up to 9
  src/main/java/dk/dtu/engine/core/WindowManager.java
  src/main/java/dk/dtu/engine/graphics/GameRulePopup.java
  src/main/java/dk/dtu/game/core/Config.java
  src/test/java/dk/dtu/core/SudokuGameTest.java
Labels: enhancement

#84 Made lives work with custom and disabled them for online play
  src/main/java/dk/dtu/engine/utility/GameClient.java
  src/main/java/dk/dtu/game/core/StartMenu.java
  src/main/java/dk/dtu/game/core/SudokuGame.java
  src/main/java/dk/dtu/game/core/solver/algorithmx/AlgorithmXSolver.java
  sudoku.db
Labels: documentation

#92 Config now uses Preferences
  src/main/java/dk/dtu/game/core/Config.java
Labels: enhancement

#90 83 localgameplay still does not work
  src/main/java/dk/dtu/engine/utility/GameClient.java
  src/main/java/dk/dtu/engine/utility/GameServer.java
  src/main/java/dk/dtu/game/core/StartMenu.java
  src/main/java/dk/dtu/game/core/SudokuGame.java
  src/main/resources/logback.xml
  sudoku.db
Labels: bug

#94 Fixed numberhub
  src/main/java/dk/dtu/engine/utility/GameClient.java
  src/main/java/dk/dtu/game/core/SudokuGame.java
Labels: bug, enhancement

#97 Fixed a bug with the timer not starting in online play
  identifier.sqlite
  src/main/java/dk/dtu/engine/core/WindowManager.java
  src/main/java/dk/dtu/engine/utility/TimerFunction.java
  src/main/java/dk/dtu/game/core/SudokuGame.java
Labels: bug

#99 Leaderbord can now be sorted
  src/main/java/dk/dtu/game/core/StartMenu.java
  src/main/java/dk/dtu/game/core/SudokuGame.java
  sudoku.db
Labels: enhancement

#96 Made killer sudoku gamemode
  src/main/java/dk/dtu/engine/graphics/Cage.java
  src/main/java/dk/dtu/engine/graphics/Cell.java
  src/main/java/dk/dtu/engine/graphics/SudokuBoardCanvas.java
  src/main/java/dk/dtu/engine/utility/JSwitchBox.java
  src/main/java/dk/dtu/game/core/Config.java
  src/main/java/dk/dtu/game/core/StartMenu.java
  src/main/java/dk/dtu/game/core/SudokuGame.java
  src/test/java/dk/dtu/core/KillerSudokuTest.java
Labels: enhancement

#102 OnlineGame Should Finilly be working
  src/main/java/dk/dtu/engine/utility/GameClient.java
  src/main/java/dk/dtu/game/core/SudokuGame.java
Labels: bug

#103 Added a progressbar for onlineplay
  src/main/java/dk/dtu/engine/core/WindowManager.java
  src/main/java/dk/dtu/engine/utility/GameClient.java
  src/main/java/dk/dtu/engine/utility/GameServer.java
  src/main/java/dk/dtu/game/core/SudokuGame.java
Labels: enhancement

#104 fixed error with irregular sudokus causing error messages
  src/main/java/dk/dtu/engine/graphics/SudokuBoardCanvas.java
  src/main/java/dk/dtu/game/core/SudokuGame.java
Labels: bug

#107 Added load and save game function
  src/main/java/dk/dtu/DropdownButtonExample.java
  src/main/java/dk/dtu/engine/core/GameEngine.java
  src/main/java/dk/dtu/engine/core/WindowManager.java
  src/main/java/dk/dtu/engine/graphics/Cage.java
  src/main/java/dk/dtu/engine/graphics/SudokuBoardCanvas.java
  src/main/java/dk/dtu/engine/utility/DatabaseSetup.java
  src/main/java/dk/dtu/engine/utility/SavedGame.java
  src/main/java/dk/dtu/engine/utility/TimerFunction.java
  src/main/java/dk/dtu/game/core/StartMenu.java
  src/main/java/dk/dtu/game/core/SudokuGame.java
  src/main/java/dk/dtu/game/core/solver/algorithmx/AlgorithmXSolver.java
  src/test/java/dk/dtu/core/KillerSudokuTest.java
  sudoku.db
Labels: enhancement

#108 MakeBuildPossible
  pom.xml
  src/main/java/dk/dtu/SudokuSolverApp.java
  src/main/resources/META-INF/MANIFEST.MF
Labels: enhancement

#110 Made darkmode and fixed some small errors
  pom.xml
  src/main/java/dk/dtu/SudokuSolverApp.java
  src/main/java/dk/dtu/engine/core/GameEngine.java
  src/main/java/dk/dtu/engine/core/StartMenuWindowManager.java
  src/main/java/dk/dtu/engine/core/WindowManager.java
  src/main/java/dk/dtu/engine/graphics/Cell.java
  src/main/java/dk/dtu/engine/graphics/GameRulePopup.java
  src/main/java/dk/dtu/engine/graphics/NumberHub.java
  src/main/java/dk/dtu/engine/graphics/SudokuBoardCanvas.java
  src/main/java/dk/dtu/engine/input/KeyboardListener.java
  src/main/java/dk/dtu/engine/input/MouseActionListener.java
  src/main/java/dk/dtu/engine/utility/CustomBoardPanel.java
  src/main/java/dk/dtu/engine/utility/CustomComponentGroup.java
  src/main/java/dk/dtu/engine/utility/CustomProgressBar.java
  src/main/java/dk/dtu/engine/utility/CustomProgressBarUI.java
  src/main/java/dk/dtu/engine/utility/GameClient.java
  src/main/java/dk/dtu/engine/utility/GameServer.java
  src/main/java/dk/dtu/engine/utility/JSwitchBox.java
  src/main/java/dk/dtu/engine/utility/Leaderboard.java
  src/main/java/dk/dtu/engine/utility/NumberDocumentFilter.java
  src/main/java/dk/dtu/engine/utility/SavedGame.java
  src/main/java/dk/dtu/engine/utility/TimerFunction.java
  src/main/java/dk/dtu/engine/utility/UpdateLeaderboard.java
  src/main/java/dk/dtu/game/core/Board.java
  src/main/java/dk/dtu/game/core/Config.java
  src/main/java/dk/dtu/game/core/Move.java
  src/main/java/dk/dtu/game/core/StartMenu.java
  src/main/java/dk/dtu/game/core/SudokuGame.java
  src/main/resources/logo.png
  src/main/resources/moon_symbol.png
  src/main/resources/pixel-frame-0.png
  src/main/resources/sun_symbol.png
  src/test/java/dk/dtu/core/StartMenuTest.java
  src/test/java/dk/dtu/core/SudokuGameTest.java
Labels: enhancement
